name: CI/CD for ECS and ECR

on:
  push:
    paths:
      - 'backend_rds/**'

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest
    environment: production

    env:
      CLUSTER_NAME: main-esc-cluster
      RDS_SERVICE_NAME: rds
      AWS_REGION: eu-central-1
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Use the env variable

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }} -f backend_rds/Dockerfile backend_rds 
          docker push ${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }}
          echo "::set-output name=image::${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}" # Сохраняем имя образа

      - name: Fetch current task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition rds \
            --query taskDefinition \
            --output json > task-definition.json

      - name: Update container image
        run: |
          jq '.containerDefinitions[0].image="${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }}"' \
          task-definition.json > new-task-definition.json

      - name: Register new task definition
        id: register-task
        run: |
          NEW_TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-definition.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "task_definition_arn=$NEW_TASK_DEF_ARN" >> $GITHUB_ENV

      - name: Update ECS service
        run: |
          aws ecs update-service \
            --cluster main-esc-cluster \
            --service rds \
            --task-definition ${{ env.task_definition_arn }}
