name: CI/CD for ECS and ECR

on:
  push:
    paths:
      - 'backend_rds/**'

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: main-esc-cluster
      RDS_SERVICE_NAME: rds
      AWS_REGION: eu-central-1
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Debug Environment Variables
        run: |
          echo "Cluster Name: $CLUSTER_NAME"
          echo "Service Name: $RDS_SERVICE_NAME"
          echo "AWS Region: $AWS_REGION"


      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}  # Use the env variable

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }} -f backend_rds/Dockerfile backend_rds 
          docker push ${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }}

      - name: Update ECS Task Definition
        id: update-task-def
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
            
            CURRENT_TASK_DEFINITION=$(aws ecs describe-task-definition \
            --task-definition your-task-definition-name \
            --query 'taskDefinition')
            
            
            NEW_TASK_DEFINITION=$(echo "$CURRENT_TASK_DEFINITION" | \
            jq --arg IMAGE_URI "${{ steps.login-ecr.outputs.registry }}/repo/rds:${{ github.sha }}" \
            '.containerDefinitions[0].image=$IMAGE_URI | del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .registeredAt, .registeredBy)')
            
            
            echo "$NEW_TASK_DEFINITION" > new-task-def.json
            aws ecs register-task-definition --cli-input-json file://new-task-def.json

            - name: Update ECS Service
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
              run: |
                
                LATEST_TASK_DEFINITION=$(aws ecs describe-task-definition \
                  --task-definition your-task-definition-name \
                  --query 'taskDefinition.taskDefinitionArn' \
                  --output text)
                
                
                aws ecs update-service \
                  --cluster your-ecs-cluster-name \
                  --service your-ecs-service-name \
                  --task-definition "$LATEST_TASK_DEFINITION"