name: CI/CD for redis_backend - ECS and ECR

on:
  push:
    paths:
      - 'backend_redis/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy Docker Image
    runs-on: ubuntu-latest

    env:
      CLUSTER_NAME: main-esc-cluster
      REDIS_SERVICE_NAME: redis
      AWS_REGION: eu-central-1
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }} # Define ECR_REPOSITORY

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 3. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # 4. Build & Push Docker image
      - name: Build & Push Docker image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }} backend_redis -f backend_redis/Dockerfile
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:${{ github.sha }}

       # 5. Download task definition
      - name: Download task definition
        run: |
          aws ecs describe-task-definition \
            --task-definition redis-task-definition \
            --query taskDefinition \
            --output json > task-definition.json

       # 6. checking task definition file
      - name: Debug task definition
        run: |
          echo "Task definition content:"
          cat task-definition.json

        # 7. Update our task definition with new image
      - name: Fill in new image ID in task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: rds
          image: ${{ steps.login-ecr.outputs.registry }}/repo/redis:${{ github.sha }}

      # 8. Deploy to ecs
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: rds
          cluster: main-esc-cluster

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster main-esc-cluster --service redis --force-new-deployment --region ${{ env.AWS_REGION }}